//! Transport-neutral publish API used by HTTP and gRPC adapters.

use std::sync::Arc;

use async_trait::async_trait;
use bytes::Bytes;
use thiserror::Error;

/// Command accepted by a configured message publisher.
#[derive(Clone, Debug)]
pub struct PublishCommand {
    /// Effective idempotency key, supplied by the caller or generated by the API.
    pub message_id: Arc<str>,
    /// Authorized tenant.
    pub tenant_id: Arc<str>,
    /// Optional routing dimensions.
    pub kind: Option<Arc<str>>,
    /// Optional routing dimensions.
    pub message_type: Option<Arc<str>>,
    /// Optional routing dimensions.
    pub channel: Option<Arc<str>>,
    /// Optional routing dimensions.
    pub actor_id: Option<Arc<str>>,
    /// Optional routing dimensions.
    pub audience_type: Option<Arc<str>>,
    /// Optional routing dimensions.
    pub audience_id: Option<Arc<str>>,
    /// Optional caller-selected ordering key, always tenant-namespaced by Kafka.
    pub ordering_key: Option<Arc<str>>,
    /// Payload MIME type.
    pub content_type: Arc<str>,
    /// Raw payload bytes.
    pub payload: Bytes,
}

impl PublishCommand {
    /// Validates metadata shared by every publish transport and backend.
    pub fn validate(&self) -> Result<(), PublishError> {
        crate::RoutingMetadata {
            message_id: Arc::clone(&self.message_id),
            tenant_id: Arc::clone(&self.tenant_id),
            kind: self.kind.clone(),
            message_type: self.message_type.clone(),
            channel: self.channel.clone(),
            actor_id: self.actor_id.clone(),
            audience_type: self.audience_type.clone(),
            audience_id: self.audience_id.clone(),
            content_type: Arc::clone(&self.content_type),
            timestamp_ms: None,
            source: None,
        }
        .validate()
        .map_err(|error| PublishError::invalid_input(error.to_string()))?;

        let content_type = self
            .content_type
            .parse::<mime::Mime>()
            .map_err(|_| PublishError::invalid_input("content_type must be a valid MIME type"))?;
        if content_type.type_() == mime::STAR || content_type.subtype() == mime::STAR {
            return Err(PublishError::invalid_input(
                "content_type wildcards are not allowed",
            ));
        }
        if let Some(ordering_key) = &self.ordering_key {
            crate::ids::validate_identifier("ordering_key", ordering_key, 256)
                .map_err(|error| PublishError::invalid_input(error.to_string()))?;
        }
        Ok(())
    }
}

/// Kafka acknowledgement returned to a caller.
#[derive(Clone, Debug)]
pub struct PublishReceipt {
    /// Effective message id.
    pub message_id: String,
    /// Kafka topic.
    pub topic: String,
    /// Kafka partition.
    pub partition: i32,
    /// Kafka offset.
    pub offset: i64,
}

/// Publish backend failure safe to map to a protocol error.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PublishErrorKind {
    /// Caller-supplied metadata violates the message contract.
    InvalidInput,
    /// The broker acknowledgement deadline elapsed.
    Timeout,
    /// The bounded Kafka producer queue was full.
    QueueFull,
    /// Kafka or another configured backend failed.
    Backend,
}

/// Publish failure with a stable classification for protocol adapters.
#[derive(Debug, Error)]
#[error("{message}")]
pub struct PublishError {
    kind: PublishErrorKind,
    message: String,
}

impl PublishError {
    /// Creates an invalid-input failure.
    pub fn invalid_input(message: impl Into<String>) -> Self {
        Self {
            kind: PublishErrorKind::InvalidInput,
            message: message.into(),
        }
    }

    /// Creates a backend failure. Adapters should log this message and return a generic
    /// public error because backend diagnostics can contain deployment details.
    pub fn backend(message: impl Into<String>) -> Self {
        Self {
            kind: PublishErrorKind::Backend,
            message: message.into(),
        }
    }

    /// Creates a broker-timeout failure.
    pub fn timeout(message: impl Into<String>) -> Self {
        Self {
            kind: PublishErrorKind::Timeout,
            message: message.into(),
        }
    }

    /// Creates a producer-queue saturation failure.
    pub fn queue_full(message: impl Into<String>) -> Self {
        Self {
            kind: PublishErrorKind::QueueFull,
            message: message.into(),
        }
    }

    /// Returns the stable failure classification.
    pub const fn kind(&self) -> PublishErrorKind {
        self.kind
    }
}

/// Asynchronous publisher abstraction implemented by Kafka.
#[async_trait]
pub trait MessagePublisher: Send + Sync {
    /// Publishes one command and waits for broker acknowledgement.
    async fn publish(&self, command: PublishCommand) -> Result<PublishReceipt, PublishError>;
}
