apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kafka-edge-router
  namespace: kafka-router
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-edge-router
