apiVersion: v1
kind: Secret
metadata:
  name: rust-kafka-edge-router
  namespace: kafka-router
type: Opaque
stringData:
  # Prefer an external secret operator. These keys are examples only.
  kafka-username: REPLACE
  kafka-password: REPLACE
